<?php
$portal_config = array ('dbconfig' => array ('db_host_name' => 'localhost:3306','db_host_instance' => 'SQLEXPRESS',   'db_user_name' => 'scalasticacrmdb', 'db_password' => 'sprekkenze72','db_name' => 'scalastica_crm','db_type' => 'mysql',),'portalconfig' => array ('default_service_leadsources_id_c' => 'd2dc840e-c041-d08d-9f53-51bf7aac9cb7',
	'baseurl' => 'http://www.scalastica.com/',
	'synchkey' => 'bxasvcvdytcvaycvayvdya',
	'glb_domain' => 'scalastica.com',
	'glb_home_url' => 'http://www.scalastica.com',
	'glb_app_dir' => '',
	'is_subdomain' => '0',
	'subdomain' => '',
	'is_ssl' => '',
	'default_lingo' => 'en',
	'portal_email' => 'info@scalastica.com',
	'portal_email_password' => 'spiceoflife72',
	'portal_title' => 'Scalastica',
	'portal_description' => 'Scalastica provides businesses with scalable Advanced Managed Services',
	'portal_keywords' => 'Scalastica,Advanced Managed Services','portal_skin' => 'scalastica',
	'portal_font_color' => '#696969',
	'portal_header_color' => '#555555',
	'portal_body_color' => '#FFFFFF',
	'portal_footer_color' => '#555555',
	'portal_border_color' => '#d3d3d3',
	'portal_style' => 'css/scalastica/scalastica.css',
	'portal_system_style' => 'css/style.php',
	'portal_style_images' => 'scalastica',
	'portal_logo' => 'logo.png',
	'portal_large_logo' => '',
	'portal_logo_height' => '50',
	'portal_logo_width' => '210',
	'portal_logo_title' => 'Scalastica',
	'portal_url' => 'http://www.scalastica.com',
	'portal_url_title' => 'Scalastica',
	'portal_copyright_text' => 'Copyright 2013+<BR>Scalastica. All rights reserved',
	'portal_copyright_url' => 'http://www.scalastica.com','google_map_api_key' => 'ABQIAAAAyKZmK71J8Tf8a6qaspgteRRnf7CX7VEdwopzFZqfDbYyK7Sb0hRX7yy8Hs98jfhLL2O7AGiF6tdNpQ', ),	  'creditsconfig' =>  array (	'base_rate' => '100',
	'base_currency' => 'ddd07ef1-8ce6-2188-ae4e-5157be0c437e',
	'partner_share' => '0.80', ),'sugarconfig' =>
  array (
	'crm_wsdl_url' => 'http://www.scalastica.com/crm/soap.php?wsdl',
	'crm_api_user' => 'admin',
	'crm_api_pass' => 'sprekkenze72',
  ),	
'facebook' =>  array ('appid' => '113318312083454',
	'api' => 'a0100d90201960e75716aa9687fcda04',
	'secret' => 'd412786ae3818b2ec86edddeace6a3ac',	'facebook_service_leadsources_id_c' => 'bfda2a47-b172-7a97-58fa-4d577adb786e',	'facebook_app_url' => 'http://apps.facebook.com/scalastica/', ),'linkedin' =>
  array (
	'appname' => 'Scalastica',
	'apikey' => 'nil7gzlv39et',
	'secret' => 'SoUqK3GP1h7eDhIb',
	'linkedin_service_leadsources_id_c' => 'dc35866e-079c-4232-8027-4d972ddd96a3',
	'linkedin_app_url' => 'http://www.scalastica.com/linkedin/',
  ),  
'google' =>
  array (
	'product_name' => 'Scalastica',
	'client_id' => '723891289975.apps.googleusercontent.com',
	'email_address' => '723891289975@developer.gserviceaccount.com',
	'client_secret' => 'baGOMP_8UfHUR6Ew9obluuGV',
	'javascript_origins' => 'http://www.scalastica.com',
	'google_service_leadsources_id_c' => '68f8a98f-d27e-945d-0942-516a0b065645',
  ),
'twitter' =>  array ('username' => 'Scalastica',
	'twitter_user_url' => 'https://twitter.com/#!/Scalastica',
	'consumer_key' => 'Iu1UdLQrMmV8jJofJXAvQ',
	'consumer_secret' => 'u55iJRpRiQtRPlAPj1mK91NxMYBwnDvWVkjJIwZMhM',
	'access_token' => '405097740-iF2yBExWBMRb3uJN7WWk6NMpoEnGfmQp1lKA0ZxT',
	'access_token_secret' => 'B6Wf5hP2nGXnu2Wy3bJ9PiMEHfbugFgooiW88uh6S4','twitter_service_leadsources_id_c' => 'dc35866e-079c-4232-8027-4d972ddd96a3',	'twitter_app_url' => 'https://twitter.com/#!/Scalastica',),'targetmarkets' =>  array ('personal' => '15709226-5214-775e-ccbe-4c9d57db0143',
	'businenss' => '23842d3d-1140-2197-ed02-4c9d57a32740',
	'government' => 'eae76b0a-481c-18e1-98bb-4c9d5754802f',  ),'dbconfigoption' => array ('persistent' => true,'autofree' => false,'debug' => 0,'seqname_format' => '%s_seq','portability' => 0,'ssl' => false,'collation' => 'utf8_general_ci',),'default_action' => 'index','default_charset' => 'UTF-8',);
?>