/*
 * JS for AccountDetails generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function AccountDetails_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_9': 'AccountDetails_mobilebutton_9',
        'mobilegrid_2': 'AccountDetails_mobilegrid_2',
        'mobilegridcell_3': 'AccountDetails_mobilegridcell_3',
        'account_name': 'AccountDetails_account_name',
        'mobilegridcell_5': 'AccountDetails_mobilegridcell_5',
        'mobilegridcell_7': 'AccountDetails_mobilegridcell_7',
        'mobilegridcell_8': 'AccountDetails_mobilegridcell_8'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'AccountDetails';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var AccountDetails_onLoad = function() {
            AccountDetails_elementsExtraJS();

            AccountDetails_deviceEvents();
            AccountDetails_windowEvents();
            AccountDetails_elementsEvents();
        };

    // screen window events


    function AccountDetails_windowEvents() {

        $('#AccountDetails').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function AccountDetails_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function AccountDetails_elementsExtraJS() {
        // screen (AccountDetails) extra code

    };

    // screen elements handler


    function AccountDetails_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#AccountDetails_mobileheader [name="mobilebutton_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#AccountDetails_mobileheader [name="mobilebutton_9"]');

    };

    $(document).off("pagebeforeshow", "#AccountDetails").on("pagebeforeshow", "#AccountDetails", function(event, ui) {
        Apperyio.CurrentScreen = "AccountDetails";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    AccountDetails_onLoad();
};

$(document).off("pagecreate", "#AccountDetails").on("pagecreate", "#AccountDetails", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    AccountDetails_js();
});