/*
 * JS for ContactsSync generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function ContactsSync_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btn_top': 'ContactsSync_btn_top',
        'device_contact_keyword': 'ContactsSync_device_contact_keyword',
        'btn_device_contact_search': 'ContactsSync_btn_device_contact_search',
        'device_contacts_grid': 'ContactsSync_device_contacts_grid',
        'mobilegridcell_3': 'ContactsSync_mobilegridcell_3',
        'lbl_device_contact_id': 'ContactsSync_lbl_device_contact_id',
        'mobilegridcell_4': 'ContactsSync_mobilegridcell_4',
        'device_contact_id': 'ContactsSync_device_contact_id',
        'mobilegridcell_5': 'ContactsSync_mobilegridcell_5',
        'lbl_device_contact_nickname': 'ContactsSync_lbl_device_contact_nickname',
        'mobilegridcell_6': 'ContactsSync_mobilegridcell_6',
        'device_contact_nickname': 'ContactsSync_device_contact_nickname',
        'mobilegridcell_7': 'ContactsSync_mobilegridcell_7',
        'mobilelabel_25': 'ContactsSync_mobilelabel_25',
        'mobilegridcell_8': 'ContactsSync_mobilegridcell_8',
        'device_contact_displayname': 'ContactsSync_device_contact_displayname',
        'mobilegridcell_9': 'ContactsSync_mobilegridcell_9',
        'mobilelabel_27': 'ContactsSync_mobilelabel_27',
        'mobilegridcell_10': 'ContactsSync_mobilegridcell_10',
        'email_grid': 'ContactsSync_email_grid',
        'mobilegridcell_32': 'ContactsSync_mobilegridcell_32',
        'device_contact_email_id': 'ContactsSync_device_contact_email_id',
        'mobilegridcell_33': 'ContactsSync_mobilegridcell_33',
        'device_contact_email': 'ContactsSync_device_contact_email',
        'mobilegridcell_45': 'ContactsSync_mobilegridcell_45',
        'mobilegridcell_46': 'ContactsSync_mobilegridcell_46',
        'device_contact_email_type': 'ContactsSync_device_contact_email_type',
        'mobilegridcell_21': 'ContactsSync_mobilegridcell_21',
        'mobilelabel_29': 'ContactsSync_mobilelabel_29',
        'mobilegridcell_22': 'ContactsSync_mobilegridcell_22',
        'phone_grid': 'ContactsSync_phone_grid',
        'mobilegridcell_39': 'ContactsSync_mobilegridcell_39',
        'device_contact_phone_id': 'ContactsSync_device_contact_phone_id',
        'mobilegridcell_40': 'ContactsSync_mobilegridcell_40',
        'device_contact_phone': 'ContactsSync_device_contact_phone',
        'mobilegridcell_41': 'ContactsSync_mobilegridcell_41',
        'mobilegridcell_42': 'ContactsSync_mobilegridcell_42',
        'device_contact_phone_type': 'ContactsSync_device_contact_phone_type',
        'mobilegridcell_23': 'ContactsSync_mobilegridcell_23',
        'lbl_device_contact_sync_status': 'ContactsSync_lbl_device_contact_sync_status',
        'mobilegridcell_24': 'ContactsSync_mobilegridcell_24',
        'device_contact_sync_status': 'ContactsSync_device_contact_sync_status'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["ContactsSync_DeviceContyacts_List_onsuccess_mapping_0"] = {
        "homeScreen": "ContactsSync",
        "directions": [

        {
            "from_name": "DeviceContyacts_List",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "ContactsSync",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data'][i]",
                "target": "$['device_contacts_grid']"

            },

            {

                "source": "$['data'][i]['id']",
                "target": "$['device_contacts_grid']['device_contact_id:text']"

            },

            {

                "source": "$['data'][i]['nickName']",
                "target": "$['device_contacts_grid']['device_contact_nickname:text']"

            },

            {

                "source": "$['data'][i]['displayName']",
                "target": "$['device_contacts_grid']['device_contact_displayname:text']"

            },

            {

                "source": "$['data'][i]['emails'][i]['value']",
                "target": "$['device_contacts_grid']['email_grid']['device_contact_email:text']"

            },

            {

                "source": "$['data'][i]['phoneNumbers'][i]['value']",
                "target": "$['device_contacts_grid']['phone_grid']['device_contact_phone:text']"

            },

            {

                "source": "$['data'][i]['emails'][i]",
                "target": "$['device_contacts_grid']['email_grid']"

            },

            {

                "source": "$['data'][i]['phoneNumbers'][i]",
                "target": "$['device_contacts_grid']['phone_grid']"

            },

            {

                "source": "$['data'][i]['phoneNumbers'][i]['type']",
                "target": "$['device_contacts_grid']['phone_grid']['device_contact_phone_type:text']"

            },

            {

                "source": "$['data'][i]['emails'][i]['type']",
                "target": "$['device_contacts_grid']['email_grid']['device_contact_email_type:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["ContactsSync_DeviceContyacts_List_onbeforesend_mapping_0"] = {
        "homeScreen": "ContactsSync",
        "directions": [

        {
            "from_name": "ContactsSync",
            "from_type": "UI",

            "to_name": "DeviceContyacts_List",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "multiple": true
                    },
                    "params": {
                        "fields": "*"
                    }
                }
            },

            "mappings": [

            {

                "source": "$['device_contact_keyword:text']",
                "target": "$['data']['options']['filter']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.DeviceContyacts_List = Apperyio.datasources.DeviceContyacts_List = new Apperyio.DataSource(DeviceContacts_List, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ContactsSync_DeviceContyacts_List_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ContactsSync_DeviceContyacts_List_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'ContactsSync';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ContactsSync_onLoad = function() {
            ContactsSync_elementsExtraJS();

            ContactsSync_deviceEvents();
            ContactsSync_windowEvents();
            ContactsSync_elementsEvents();
        };

    // screen window events


    function ContactsSync_windowEvents() {

        $('#ContactsSync').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ContactsSync_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ContactsSync_elementsExtraJS() {
        // screen (ContactsSync) extra code

        /* device_contact_sync_status */

        $("#ContactsSync_device_contact_sync_status").parent().find(".ui-flipswitch-on").attr("tabindex", "6");

    };

    // screen elements handler


    function ContactsSync_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ContactsSync_mobileheader [name="btn_top"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: true
                    });

                }
            },
        }, '#ContactsSync_mobileheader [name="btn_top"]');

        $(document).off("click", '#ContactsSync_mobilecontainer [name="btn_device_contact_search"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        DeviceContyacts_List.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#ContactsSync_mobilecontainer [name="btn_device_contact_search"]');

    };

    $(document).off("pagebeforeshow", "#ContactsSync").on("pagebeforeshow", "#ContactsSync", function(event, ui) {
        Apperyio.CurrentScreen = "ContactsSync";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ContactsSync_onLoad();
};

$(document).off("pagecreate", "#ContactsSync").on("pagecreate", "#ContactsSync", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ContactsSync_js();
});