/*
 * JS for Events generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Events",
    "location": "Events.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function Events_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btn_home': 'Events_btn_home',
        'mobilenavbar_98': 'Events_mobilenavbar_98',
        'mobilenavbaritem_99': 'Events_mobilenavbaritem_99',
        'mobilenavbaritem_100': 'Events_mobilenavbaritem_100',
        'btn_add_event_new': 'Events_btn_add_event_new',
        'keyword': 'Events_keyword',
        'start': 'Events_start',
        'search_button': 'Events_search_button',
        'events_grid': 'Events_events_grid',
        'event_grid_cell_name': 'Events_event_grid_cell_name',
        'event_name': 'Events_event_name',
        'event_grid_cell_image': 'Events_event_grid_cell_image',
        'event_image': 'Events_event_image',
        'event_grid_cell_category': 'Events_event_grid_cell_category',
        'event_catgeory': 'Events_event_catgeory',
        'event_grid_cell_latitude': 'Events_event_grid_cell_latitude',
        'event_latitude': 'Events_event_latitude',
        'event_grid_cell_longitude': 'Events_event_grid_cell_longitude',
        'event_longitude': 'Events_event_longitude',
        'event_id': 'Events_event_id',
        'event_grid_cell_map': 'Events_event_grid_cell_map'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Events_EventsListService_onbeforesend_mapping_0"] = {
        "homeScreen": "Events",
        "directions": [

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventsListService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "X-Appery-Brand": "b4934b04-ae31-495e-846e-714d3da4ac87"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventsListService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "X-Appery-Brand": "b4934b04-ae31-495e-846e-714d3da4ac87"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "auth",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventsListService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "X-Appery-Brand": "b4934b04-ae31-495e-846e-714d3da4ac87"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['auth']"

            }

            ]
        },

        {
            "from_name": "Events",
            "from_type": "UI",

            "to_name": "EventsListService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "X-Appery-Brand": "b4934b04-ae31-495e-846e-714d3da4ac87"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['keyword:text']",
                "target": "$['parameters']['keyword']"

            },

            {

                "source": "$['start:text']",
                "target": "$['parameters']['search_date']"

            }

            ]
        },

        {
            "from_name": "val",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventsListService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "X-Appery-Brand": "b4934b04-ae31-495e-846e-714d3da4ac87"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['valtype']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Events_EventsListService_onsuccess_mapping_0"] = {
        "homeScreen": "Events",
        "directions": [

        {

            "to_name": "Events",
            "to_type": "UI",

            "mappings": [

            {

                "target": "$['event_name:text']"

            },

            {

                "target": "$['event_catgeory:text']"

            },

            {

                "target": "$['event_longitude:text']"

            }

            ]
        },

        {
            "from_name": "EventsListService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Events",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['events'][0]['event_image_url']",
                "target": "$['event_image:image']"

            },

            {

                "source": "$['body']['events'][0]['latitude']",
                "target": "$['event_latitude:text']"

            },

            {

                "source": "$['body']['events'][0]['event_id']",
                "target": "$['event_id:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.EventsListService = Apperyio.datasources.EventsListService = new Apperyio.DataSource(RESTService_Events_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Events_EventsListService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Events");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Events_EventsListService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Events';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Events_onLoad = function() {
            Events_elementsExtraJS();

            try {
                EventsListService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            Events_deviceEvents();
            Events_windowEvents();
            Events_elementsEvents();
        };

    // screen window events


    function Events_windowEvents() {

        $('#Events').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Events_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Events_elementsExtraJS() {
        // screen (Events) extra code

    };

    // screen elements handler


    function Events_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Events_header_event [name="btn_home"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#Events_header_event [name="btn_home"]');

        $(document).off("click", '#Events_header_event [name="mobilenavbaritem_99"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", "my_events")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('Events', {
                        reverse: false
                    });

                }
            },
        }, '#Events_header_event [name="mobilenavbaritem_99"]');
        $(document).off("click", '#Events_header_event [name="mobilenavbaritem_100"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", "public_events")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('Events', {
                        reverse: false
                    });

                }
            },
        }, '#Events_header_event [name="mobilenavbaritem_100"]');
        $(document).off("click", '#Events_header_event [name="btn_add_event_new"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('EventAdd', {
                        reverse: false
                    });

                }
            },
        }, '#Events_header_event [name="btn_add_event_new"]');

        $(document).off("click", '#Events_mobilecontainer [name="search_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        EventsListService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Events_mobilecontainer [name="search_button"]');

        $(document).off("click", '#Events_mobilecontainer [name="event_name"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('event_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('EventView', {
                        transition: 'slideup',
                        reverse: false
                    });

                }
            },
        }, '#Events_mobilecontainer [name="event_name"]');

    };

    $(document).off("pagebeforeshow", "#Events").on("pagebeforeshow", "#Events", function(event, ui) {
        Apperyio.CurrentScreen = "Events";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Events_onLoad();
};

$(document).off("pagecreate", "#Events").on("pagecreate", "#Events", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Events_js();
});