/*
 * JS for EventView generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function EventView_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btn_home': 'EventView_btn_home',
        'mobilenavbar_98': 'EventView_mobilenavbar_98',
        'btn_my_events': 'EventView_btn_my_events',
        'btn_public_events': 'EventView_btn_public_events',
        'btn_add_event_new': 'EventView_btn_add_event_new',
        'btn_add_event_parent': 'EventView_btn_add_event_parent',
        'btn_add_event_sub': 'EventView_btn_add_event_sub',
        'btn_add_event_related': 'EventView_btn_add_event_related',
        'btn_add_event_edit': 'EventView_btn_add_event_edit',
        'btn_share_event': 'EventView_btn_share_event',
        'events_grid': 'EventView_events_grid',
        'event_grid_cell_name': 'EventView_event_grid_cell_name',
        'rest_response': 'EventView_rest_response',
        'event_id': 'EventView_event_id',
        'btn_parent_event': 'EventView_btn_parent_event',
        'event_grid_cell_image': 'EventView_event_grid_cell_image',
        'event_name': 'EventView_event_name',
        'event_grid_cell_category': 'EventView_event_grid_cell_category',
        'start_date': 'EventView_start_date',
        'event_grid_cell_latitude': 'EventView_event_grid_cell_latitude',
        'end_date': 'EventView_end_date',
        'gridcell_image': 'EventView_gridcell_image',
        'event_image': 'EventView_event_image',
        'event_grid_cell_map': 'EventView_event_grid_cell_map',
        'event_catgeory': 'EventView_event_catgeory',
        'mobilegridcell_102': 'EventView_mobilegridcell_102',
        'event_description': 'EventView_event_description',
        'gridcell_latitude': 'EventView_gridcell_latitude',
        'event_latitude': 'EventView_event_latitude',
        'gridcell_longitude': 'EventView_gridcell_longitude',
        'event_longitude': 'EventView_event_longitude',
        'gridcell_map': 'EventView_gridcell_map',
        'googlemap': 'EventView_googlemap',
        'marker_73': 'EventView_marker_73',
        'mobilegridcell_106': 'EventView_mobilegridcell_106',
        'parent_id': 'EventView_parent_id',
        'mobilegridcell_112': 'EventView_mobilegridcell_112',
        'mobilegridcell_113': 'EventView_mobilegridcell_113',
        'mobilebutton_138': 'EventView_mobilebutton_138',
        'EventGrid_118': 'EventView_EventGrid_118',
        'mobilegridcell_99_119': 'EventView_mobilegridcell_99_119',
        'event_name_120': 'EventView_event_name_120',
        'mobilegridcell_101_121': 'EventView_mobilegridcell_101_121',
        'event_image_122': 'EventView_event_image_122',
        'mobilegridcell_103_123': 'EventView_mobilegridcell_103_123',
        'event_catgeory_124': 'EventView_event_catgeory_124',
        'mobilegridcell_104_125': 'EventView_mobilegridcell_104_125',
        'start_date_126': 'EventView_start_date_126',
        'mobilegridcell_105_127': 'EventView_mobilegridcell_105_127',
        'end_date_128': 'EventView_end_date_128',
        'mobilegridcell_106_129': 'EventView_mobilegridcell_106_129',
        'event_latitude_130': 'EventView_event_latitude_130',
        'mobilegridcell_107_131': 'EventView_mobilegridcell_107_131',
        'event_longitude_132': 'EventView_event_longitude_132',
        'mobilegridcell_111_133': 'EventView_mobilegridcell_111_133',
        'event_id_134': 'EventView_event_id_134',
        'mobilegridcell_120_135': 'EventView_mobilegridcell_120_135',
        'image_136': 'EventView_image_136',
        'share_event_id': 'EventView_share_event_id',
        'select_recipient_types': 'EventView_select_recipient_types',
        'select_recipient_types-0': 'EventView_select_recipient_types-0',
        'message_subject': 'EventView_message_subject',
        'message_body': 'EventView_message_body',
        'api_response': 'EventView_api_response',
        'event_share_email': 'EventView_event_share_email',
        'btn_share_event_submit': 'EventView_btn_share_event_submit',
        'btn_closer': 'EventView_btn_closer'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["EventView_EventViewService_onsuccess_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "EventViewService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "EventView",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['events'][0]['name']",
                "target": "$['event_name:text']"

            },

            {

                "source": "$['body']['events'][0]['latitude']",
                "target": "$['event_latitude:text']"

            },

            {

                "source": "$['body']['events'][0]['longitude']",
                "target": "$['event_longitude:text']"

            },

            {

                "source": "$['body']['events'][0]['category_id']",
                "target": "$['event_catgeory:text']"

            },

            {

                "source": "$['body']['events'][0]['event_image_url']",
                "target": "$['event_image:image']"

            },

            {

                "source": "$['body']['events'][0]['end_date']",
                "target": "$['end_date:text']"

            },

            {

                "source": "$['body']['events'][0]['start_date']",
                "target": "$['start_date:text']"

            },

            {

                "source": "$['body']['events'][0]['parent_id']",
                "target": "$['parent_id:text']"

            },

            {

                "source": "$['body']['events'][0]['event_id']",
                "target": "$['event_id:text']"

            },

            {

                "source": "$['body']['events'][0]['description']",
                "target": "$['event_description:text']"

            },

            {

                "source": "$['body']['events'][0]['parent_name']",
                "target": "$['btn_parent_event:text']"

            },

            {

                "source": "$['body']['events'][0]['latitude']",
                "target": "$['googlemap:latitude']"

            },

            {

                "source": "$['body']['events'][0]['longitude']",
                "target": "$['googlemap:longitude']"

            },

            {

                "source": "$['body']['events'][0]['street']",
                "target": "$['googlemap:address']"

            },

            {

                "source": "$['body']['events'][0]['name']",
                "target_transformation": function(value, element) {
                    if (value) {
                        return "Shared Event: " + value;
                    }
                },
                "target": "$['message_subject:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_EventViewService_onbeforesend_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventViewService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventViewService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "valtype",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventViewService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['valtype']"

            }

            ]
        },

        {
            "from_name": "val",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventViewService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['val']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_ParentEventListingsService_onbeforesend_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "ParentEventListingsService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "ParentEventListingsService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "val",
            "from_type": "LOCAL_STORAGE",

            "to_name": "ParentEventListingsService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "ParEvents"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['val']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_ParentEventListingsService_onsuccess_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "ParentEventListingsService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "api_response",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['api_response']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "ParentEventListingsService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "EventView",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['events'][i]",
                "target": "$['EventGrid_118']"

            },

            {

                "source": "$['body']['events'][i]['name']",
                "target": "$['EventGrid_118']['event_name_120:text']"

            },

            {

                "source": "$['body']['events'][i]['start_date']",
                "target": "$['EventGrid_118']['start_date_126:text']"

            },

            {

                "source": "$['body']['events'][i]['end_date']",
                "target": "$['EventGrid_118']['end_date_128:text']"

            },

            {

                "source": "$['body']['events'][i]['event_id']",
                "target": "$['EventGrid_118']['event_id_134:text']"

            },

            {

                "source": "$['body']['events'][i]['event_image_url']",
                "target": "$['EventGrid_118']['event_image_122:image']"

            },

            {

                "source": "$['body']['events'][i]['category_name']",
                "target": "$['EventGrid_118']['event_catgeory_124:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_RecipientTypes_onsuccess_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "RecipientTypes",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "EventView",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['recipient_types'][i]",
                "target": "$['select_recipient_types-0']"

            },

            {

                "source": "$['body']['recipient_types'][i]['id']",
                "target": "$['select_recipient_types-0:value']"

            },

            {

                "source": "$['body']['recipient_types'][i]['type']",
                "target": "$['select_recipient_types-0:label']"

            }

            ]
        },

        {
            "from_name": "RecipientTypes",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "temparray",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['recipient_types'][i]",
                "target": "$[i]"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_RecipientTypes_onbeforesend_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "sess_facebook",
            "from_type": "SESSION_STORAGE",

            "to_name": "RecipientTypes",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_fb']"

            }

            ]
        },

        {
            "from_name": "sess_google",
            "from_type": "SESSION_STORAGE",

            "to_name": "RecipientTypes",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_gg']"

            }

            ]
        },

        {
            "from_name": "sess_linkedin",
            "from_type": "SESSION_STORAGE",

            "to_name": "RecipientTypes",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_li']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "RecipientTypes",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "RecipientTypes",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "EventView",
            "from_type": "UI",

            "to_name": "RecipientTypes",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['select_recipient_types-0:value']",
                "target": "$['parameters']['recipient_types']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_MessagesPost_onbeforesend_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "EventView",
            "from_type": "UI",

            "to_name": "MessagesPost",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "valtype": "Events"
                }
            },

            "mappings": [

            {

                "source": "$['share_event_id:text']",
                "target": "$['body']['message_id']"

            },

            {

                "source": "$['share_event_id:text']",
                "target": "$['body']['val']"

            },

            {

                "source": "$['message_body:text']",
                "target": "$['body']['message_body']"

            },

            {

                "source": "$['message_subject:text']",
                "target": "$['body']['message_subject']"

            },

            {

                "source": "$['select_recipient_types:selectedMenuItem']",
                "target": "$['body']['recipient_types']"

            }

            ]
        },

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "MessagesPost",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "valtype": "Events"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "MessagesPost",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "valtype": "Events"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "sess_facebook",
            "from_type": "SESSION_STORAGE",

            "to_name": "MessagesPost",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "valtype": "Events"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_fb']"

            }

            ]
        },

        {
            "from_name": "sess_linkedin",
            "from_type": "SESSION_STORAGE",

            "to_name": "MessagesPost",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "valtype": "Events"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_li']"

            }

            ]
        },

        {
            "from_name": "sess_google",
            "from_type": "SESSION_STORAGE",

            "to_name": "MessagesPost",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "valtype": "Events"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_gg']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventView_MessagesPost_onsuccess_mapping_0"] = {
        "homeScreen": "EventView",
        "directions": [

        {
            "from_name": "MessagesPost",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "EventView",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['api_message']",
                "target": "$['api_response:text']"

            }

            ]
        },

        {
            "from_name": "MessagesPost",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "val",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['message_id']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.EventViewService = Apperyio.datasources.EventViewService = new Apperyio.DataSource(RESTService_Events_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_EventViewService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
/*
var original_description = Apperyio('event_description').text();
var lb_description = original_description.replace(/(?:\r\n|\r|\n)/g, '<br />');

if (isHTML(original_description)){
   } else {
   Apperyio('event_description').text(lb_description);
   }
*/

            var parent_id = Apperyio('parent_id').text();
            if (parent_id === null || parent_id == "NULL" || parent_id == NULL || parent_id === '') {
                Apperyio('btn_parent_event').hide();
            } else {
                Apperyio('btn_parent_event').show();
            }

            var event_image = Apperyio('event_image').text();
            if (event_image === null || event_image == "NULL" || event_image == NULL || event_image === '' || event_image === 'files/resources/image/no-image.jpg') {
                //Apperyio('event_image').show();
                Apperyio('gridcell_image').hide();
            } else {
                Apperyio('gridcell_image').show();
                //Apperyio('event_image').hide();
                //$('[dsid="event_image"]').hide();
            }

            var event_latitude = Apperyio('event_latitude').text();
            //var event_longitude = Apperyio('event_longitude').text();
            //if (event_latitude === null || event_latitude === "null" || event_latitude === "NULL" || event_latitude === NULL  || event_latitude === ''){
            if (event_latitude) {
                Apperyio('gridcell_map').show();
                //Apperyio('googlemap').show();
                //$('[dsid="googlemap"]').hide();
                Apperyio('gridcell_longitude').show();
                Apperyio('gridcell_latitude').show();
            } else {
                Apperyio('gridcell_map').hide();
                Apperyio('gridcell_longitude').hide();
                Apperyio('gridcell_latitude').hide();
            };

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_EventViewService_onsuccess_mapping_0"]);
            //var parent_event = Apperyio.storage.parent_id.get();
            //var parent_id = Apperyio('parent_id').val();
            //var api_response = requestParams.api_response;
            //var api_response = Apperyio.storage.api_response.get();
            //if (api_response === "OK"){
            //   ParentEventListingsService.execute({});
            //   }
            //var event_name = Appery("event_name").val();
            //Appery("message_subject").text("Sharing an event with you: "+event_name);
/*
var fullresponse = JSON.stringify(data);
//Apperyio("rest_response").text(fullresponse);
var parent_id = JSON.parse(fullresponse).parent_id;
var event_image = JSON.parse(fullresponse).event_image_url;
var event_longitude = JSON.parse(fullresponse).longitude;
var event_latitude = JSON.parse(fullresponse).latitude;
var original_description = JSON.parse(fullresponse).description;
*/
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.ParentEventListingsService = Apperyio.datasources.ParentEventListingsService = new Apperyio.DataSource(RESTService_Events_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_ParentEventListingsService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_ParentEventListingsService_onsuccess_mapping_0"]);
            //var api_response = requestParams.api_response;
            //var api_response = Apperyio.storage.api_response.get();
            //if (api_response === "OK"){
            //   Apperyio('EventGrid_114').show();
            //   } else {
            //   Apperyio('EventGrid_114').hide();
            //   };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.RecipientTypes = Apperyio.datasources.RecipientTypes = new Apperyio.DataSource(RESTService_RecipientTypes, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_RecipientTypes_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_RecipientTypes_onsuccess_mapping_0"]);
/*
var recipient_types_json = JSON.stringify(data);
var blah;

//Apperyio("rest_response").text(recipient_types_json);

// The item selected
var recipient_type = Appery("btn_recipient_types").val();
blah = "Recipient Type Selected: " + recipient_type + "\n";

// Get the recipient array from the content

var recipient_types_array = JSON.parse(recipient_types_json).recipient_types;
var show_email = false;

    for (var i = 0; i < recipient_types_array.length; i++) {
        //
        blah = blah + ", " + recipient_types_array[i].method;
        blah = blah + ", " + recipient_types_array[i].id;
        
        if (recipient_types_array[i].method == 'textbox' && recipient_types_array[i].id == recipient_type) {
            //If the same id already exists increment quantity by 1
            //recipient_types_array[i].quantity += 1;
            //recipient_types_array[i].price += cart[i].price;
            //Apperyio('event_share_email').show();

            show_email = true;
            break;
        }
    }

Apperyio("rest_response").text(blah);
*/
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.MessagesPost = Apperyio.datasources.MessagesPost = new Apperyio.DataSource(RESTService_Messages_post, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_MessagesPost_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventView_MessagesPost_onsuccess_mapping_0"]);
            try {
                $a.storage["valtype"].update("$", "Messages")
            } catch (e) {
                console.error(e)
            };
            toggle('EventView_api_response', 'mob', 'true');
            toggle('EventView_message_body', 'mob', 'false');
            toggle('EventView_event_share_email', 'mob', 'false');
            toggle('EventView_message_subject', 'mob', 'false');
            toggle('EventView_btn_share_event_submit', 'mob', 'false');
            toggle('EventView_select_recipient_types', 'mob', 'false');
            toggle('EventView_btn_closer', 'mob', 'true');
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'EventView';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var EventView_onLoad = function() {
            EventView_elementsExtraJS();

            var sess_con = Apperyio.storage.sess_con.get();
            var sess_acc = Apperyio.storage.sess_acc.get();
            var event_acc = Apperyio('account_id').val();
            if (sess_con) {
                Apperyio('btn_add_event_new').show();
                Apperyio('btn_share_event').show();
                if (event_acc == sess_acc) {
                    Apperyio('btn_add_event_parent').show();
                    Apperyio('btn_add_event_edit').show();
                } else {
                    Apperyio('btn_add_event_parent').hide();
                    Apperyio('btn_add_event_edit').hide();
                }

                Apperyio('btn_add_event_sub').show();
                Apperyio('btn_add_event_related').show();

                //Apperyio('top_menu_register').hide();
            } else {
                Apperyio('btn_my_events').hide();
                Apperyio('btn_add_event_new').hide();
                Apperyio('btn_add_event_parent').hide();
                Apperyio('btn_add_event_edit').hide();
                Apperyio('btn_add_event_sub').hide();
                Apperyio('btn_add_event_related').hide();

            };
            try {
                EventViewService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            EventView_deviceEvents();
            EventView_windowEvents();
            EventView_elementsEvents();
        };

    // screen window events


    function EventView_windowEvents() {

        $('#EventView').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function EventView_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function EventView_elementsExtraJS() {
        // screen (EventView) extra code

        /* googlemap */

        $("[name = 'googlemap']").wrap("<div/>");
        $("[name = 'googlemap']").parent().css("margin-left", $("[name = 'googlemap']").css("margin-left"));
        $("[name = 'googlemap']").parent().css("margin-right", $("[name = 'googlemap']").css("margin-right"));
        $("[name = 'googlemap']").css("margin-left", '0');
        $("[name = 'googlemap']").css("margin-right", '0');

        var googlemap_options = {
            markerSourceName: "googlemap_markers",
            latitude: "",
            longitude: "",
            address: "",
            zoom: 10,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap', new Apperyio.ApperyMapComponent("googlemap", googlemap_options));
        $("[name='googlemap_markers'] [apperytype='marker']").attr("reRender", "googlemap");
        $(":mobile-pagecontainer").off("pagecontainershow.EventView_mobilecontainer").on("pagecontainershow.EventView_mobilecontainer", function(event, ui) {
            if (($('#EventView_googlemap', ui.toPage).length > 0) && (Apperyio('googlemap') != undefined)) {
                Apperyio('googlemap').refresh();
            }
        });

        /* pop_share_event */
        $("#EventView_pop_share_event").popup("option", "positionTo", "window");

        /* select_recipient_types */

        $("#EventView_select_recipient_types").parent().find("a.ui-btn").attr("tabindex", "23");

    };

    // screen elements handler


    function EventView_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#EventView_header_event [name="btn_home"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'flip',
                        reverse: true
                    });

                }
            },
        }, '#EventView_header_event [name="btn_home"]');

        $(document).off("click", '#EventView_header_event [name="btn_public_events"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'startScreen.html';
                    }, 0);
                    try {
                        $a.storage["action"].update("$", "public_events")
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#EventView_header_event [name="btn_public_events"]');
        $(document).off("click", '#EventView_header_event [name="btn_add_event_new"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('EventAdd', {
                        reverse: false
                    });

                }
            },
        }, '#EventView_header_event [name="btn_add_event_new"]');

        $(document).off("click", '#EventView_mobilecontainer [name="btn_add_event_parent"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["valtype"].update("$", "Events")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('event_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["action"].update("$", "add_parent")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('EventAdd', {
                        reverse: false
                    });

                }
            },
        }, '#EventView_mobilecontainer [name="btn_add_event_parent"]');
        $(document).off("click", '#EventView_mobilecontainer [name="btn_add_event_sub"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('event_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["valtype"].update("$", "Events")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["action"].update("$", "add_child")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('EventAdd', {
                        reverse: false
                    });

                }
            },
        }, '#EventView_mobilecontainer [name="btn_add_event_sub"]');
        $(document).off("click", '#EventView_mobilecontainer [name="btn_add_event_related"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('event_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["valtype"].update("$", "Events")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["action"].update("$", "add_related")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('EventAdd', {
                        reverse: false
                    });

                }
            },
        }, '#EventView_mobilecontainer [name="btn_add_event_related"]');
        $(document).off("click", '#EventView_mobilecontainer [name="btn_add_event_edit"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('event_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["valtype"].update("$", "Events")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["action"].update("$", "edit")
                    } catch (e) {
                        console.error(e)
                    };
                    setTimeout(function() {
                        window.location = 'EventAdd.html';
                    }, 0);

                }
            },
        }, '#EventView_mobilecontainer [name="btn_add_event_edit"]');
        $(document).off("click", '#EventView_mobilecontainer [name="btn_share_event"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("pop_share_event");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };
                    try {
                        $a.c15r("share_event_id", "set", "text", $a.storage["val"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        RecipientTypes.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#EventView_mobilecontainer [name="btn_share_event"]');

        $(document).off("click", '#EventView_mobilecontainer [name="btn_parent_event"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('parent_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["valtype"].update("$", "Events")
                    } catch (e) {
                        console.error(e)
                    };
                    setTimeout(function() {
                        window.location = 'EventView.html';
                    }, 0);

                }
            },
        }, '#EventView_mobilecontainer [name="btn_parent_event"]');

        $(document).off("click", '#EventView_mobilecontainer [name="mobilebutton_138"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        ParentEventListingsService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    toggle('EventView_EventGrid_118', 'mob', 'true');

                }
            },
        }, '#EventView_mobilecontainer [name="mobilebutton_138"]');

        $(document).off("click", '#EventView_mobilecontainer [name="event_name_120"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["val"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('event_id_134', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["valtype"].update("$", "Events")
                    } catch (e) {
                        console.error(e)
                    };
                    setTimeout(function() {
                        window.location = 'EventView.html';
                    }, 0);

                }
            },
        }, '#EventView_mobilecontainer [name="event_name_120"]');

        $(document).off("change", '#EventView_pop_share_event [name="select_recipient_types"]').on({
            change: function(event) { //var recipient_type = Appery("recipient_types").find("option:selected").text();
                //var recipient_type = Appery("recipient_types").val();
                //if (recipient_type === 'd8ba0615-94b3-78a5-51e4-5559de992b1c'){
                // Hide on each new selection until email
                Apperyio('event_share_email').hide();

                // The item selected
                var recipient_type = Appery("select_recipient_types").val();
                //blah = "Recipient Type Selected: " + recipient_type + "\n";
                // Get the recipient array from the content
                var recipient_types_array = Apperyio.storage.temparray.get();
                //var recipient_types_array = JSON.parse(recipient_types_json).recipient_types;
                var show_email = false;

                for (var i = 0; i < recipient_types_array.length; i++) {
                    //
                    //blah = blah + "Method: " + recipient_types_array[i].method + "\n";
                    //blah = blah + "Method: " + recipient_types_array[i].method + "\n";
                    //blah = blah + ", " + recipient_types_array[i].id;
                    if (recipient_types_array[i].method == 'textbox' && recipient_types_array[i].id == recipient_type) {
                        //If the same id already exists increment quantity by 1
                        //recipient_types_array[i].quantity += 1;
                        //recipient_types_array[i].price += cart[i].price;
                        //Apperyio('event_share_email').show();
                        show_email = true;
                        break;
                    }
                }

                //Apperyio("rest_response").text(blah);
                if (show_email) {
                    Apperyio('event_share_email').show();
                };
            },
        }, '#EventView_pop_share_event [name="select_recipient_types"]');

        $(document).off("click", '#EventView_pop_share_event [name="btn_share_event_submit"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        MessagesPost.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#EventView_pop_share_event [name="btn_share_event_submit"]');
        $(document).off("click", '#EventView_pop_share_event [name="btn_closer"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('pop_share_event').popup('close');

                }
            },
        }, '#EventView_pop_share_event [name="btn_closer"]');

    };

    $(document).off("pagebeforeshow", "#EventView").on("pagebeforeshow", "#EventView", function(event, ui) {
        Apperyio.CurrentScreen = "EventView";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    EventView_onLoad();
};

$(document).off("pagecreate", "#EventView").on("pagecreate", "#EventView", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    EventView_js();
});