/*
 * JS for EventAdd generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function EventAdd_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btn_home': 'EventAdd_btn_home',
        'event_id': 'EventAdd_event_id',
        'parent_event': 'EventAdd_parent_event',
        'event_name': 'EventAdd_event_name',
        'categories': 'EventAdd_categories',
        'categories-0': 'EventAdd_categories-0',
        'start_date': 'EventAdd_start_date',
        'end_date': 'EventAdd_end_date',
        'location_name': 'EventAdd_location_name',
        'latitude': 'EventAdd_latitude',
        'longitude': 'EventAdd_longitude',
        'description': 'EventAdd_description',
        'btn_submit_event': 'EventAdd_btn_submit_event'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["EventAdd_EventAdd_onsuccess_mapping_0"] = {
        "homeScreen": "EventAdd",
        "directions": [

        {
            "from_name": "EventAdd",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "val",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['event_id']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "EventAdd",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "api_sess",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['api_sess']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "EventAdd",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "api_response",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['api_response']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventAdd_EventAdd_onbeforesend_mapping_0"] = {
        "homeScreen": "EventAdd",
        "directions": [

        {
            "from_name": "EventAdd",
            "from_type": "UI",

            "to_name": "EventAdd",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['description:text']",
                "target": "$['body']['event_description']"

            },

            {

                "source": "$['event_name:text']",
                "target": "$['body']['event_name']"

            },

            {

                "source": "$['latitude:text']",
                "target": "$['body']['latitude']"

            },

            {

                "source": "$['longitude:text']",
                "target": "$['body']['longitude']"

            },

            {

                "source": "$['categories:selectedMenuItem']",
                "target": "$['body']['category_id']"

            },

            {

                "source": "$['start_date:defaultDateValue']",
                "target": "$['body']['start_date']"

            },

            {

                "source": "$['end_date:defaultDateValue']",
                "target": "$['body']['end_date']"

            },

            {

                "source": "$['location_name:text']",
                "target": "$['body']['location']"

            },

            {

                "source": "$['event_id:text']",
                "target": "$['body']['event_id']"

            }

            ]
        },

        {
            "from_name": "action",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventAdd",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['action']"

            }

            ]
        },

        {
            "from_name": "valtype",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventAdd",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['valtype']"

            }

            ]
        },

        {
            "from_name": "val",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventAdd",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['val']"

            }

            ]
        },

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventAdd",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventAdd",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['sess_acc']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventAdd_Categories_onbeforesend_mapping_0"] = {
        "homeScreen": "EventAdd",
        "directions": [

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "Categories",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "Categories",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "auth",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Categories",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['auth']"

            }

            ]
        },

        {
            "from_name": "EventAdd",
            "from_type": "UI",

            "to_name": "Categories",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['categories-0:value']",
                "target": "$['parameters']['id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventAdd_Categories_onsuccess_mapping_0"] = {
        "homeScreen": "EventAdd",
        "directions": [

        {
            "from_name": "Categories",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "EventAdd",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['cats'][i]",
                "target": "$['categories-0']"

            },

            {

                "source": "$['body']['cats'][i]['id']",
                "target": "$['categories-0:value']"

            },

            {

                "source": "$['body']['cats'][i]['name']",
                "target": "$['categories-0:label']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventAdd_EventEdit_onbeforesend_mapping_0"] = {
        "homeScreen": "EventAdd",
        "directions": [

        {
            "from_name": "val",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventEdit",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['val']"

            }

            ]
        },

        {
            "from_name": "valtype",
            "from_type": "LOCAL_STORAGE",

            "to_name": "EventEdit",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['valtype']"

            }

            ]
        },

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventEdit",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "EventEdit",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["EventAdd_EventEdit_onsuccess_mapping_0"] = {
        "homeScreen": "EventAdd",
        "directions": [

        {
            "from_name": "EventEdit",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "EventAdd",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['events'][0]['event_id']",
                "target": "$['event_id:text']"

            },

            {

                "source": "$['body']['events'][0]['name']",
                "target": "$['event_name:text']"

            },

            {

                "source": "$['body']['events'][0]['start_date']",
                "target": "$['start_date:defaultDateValue']"

            },

            {

                "source": "$['body']['events'][0]['end_date']",
                "target": "$['end_date:defaultDateValue']"

            },

            {

                "source": "$['body']['events'][0]['latitude']",
                "target": "$['latitude:text']"

            },

            {

                "source": "$['body']['events'][0]['longitude']",
                "target": "$['longitude:text']"

            },

            {

                "source": "$['body']['events'][0]['description']",
                "target": "$['description:text']"

            },

            {

                "source": "$['body']['events'][0]['location']",
                "target": "$['location_name:text']"

            },

            {

                "source": "$['body']['events'][0]['category_id']",
                "target": "$['categories-0:value']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.EventAdd = Apperyio.datasources.EventAdd = new Apperyio.DataSource(RESTService_Events_post, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventAdd_EventAdd_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventAdd_EventAdd_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Categories = Apperyio.datasources.Categories = new Apperyio.DataSource(RESTService_Categories_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventAdd_Categories_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventAdd_Categories_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.EventEdit = Apperyio.datasources.EventEdit = new Apperyio.DataSource(RESTService_Events_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["EventAdd_EventEdit_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            try {
                Categories.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["EventAdd_EventEdit_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'EventAdd';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var EventAdd_onLoad = function() {
            EventAdd_elementsExtraJS();

            // If event_id
            // Change header to Edit Event
            //var dateElement = Appery("date");
            //dateElement.setProperty("start_date", $.datepicker.formatDate(dateElement.datepicker_dataPickerOptions.dateFormat, new Date()));
            var action = Apperyio.storage.action.get();
            if (action == 'edit') {
                EventEdit.execute();
            }
            var start_dateElement = Appery("start_date");
            var end_dateElement = Appery("end_date");
            var start_date = new Date();
            var end_date = new Date();
            //var start_dateVal = Appery("start_date").val(); 
            //var end_dateVal = Appery("end_date").val();
            //if (!start_dateVal){
            start_dateElement.setProperty("defaultDateValue", $.datepicker.formatDate(start_dateElement.datepicker_dataPickerOptions.dateFormat, start_date));
            // }
            //if (!end_dateVal){
            end_date.setDate(end_date.getDate() + 1);
            end_dateElement.setProperty("defaultDateValue", $.datepicker.formatDate(end_dateElement.datepicker_dataPickerOptions.dateFormat, end_date));
            // }
            ;

            EventAdd_deviceEvents();
            EventAdd_windowEvents();
            EventAdd_elementsEvents();
        };

    // screen window events


    function EventAdd_windowEvents() {

        $('#EventAdd').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function EventAdd_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function EventAdd_elementsExtraJS() {
        // screen (EventAdd) extra code

        /* categories */

        $("#EventAdd_categories").parent().find("a.ui-btn").attr("tabindex", "3");

        /* start_date */

        EventAdd_start_date_selector = "#EventAdd_start_date";
        EventAdd_start_date_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 1,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        EventAdd_start_date_dataPickerOptions.defaultDate = new Date("08/20/2015");

        Apperyio.__registerComponent('start_date', new Apperyio.ApperyMobileDatePickerComponent("EventAdd_start_date", EventAdd_start_date_dataPickerOptions));

        /* end_date */

        EventAdd_end_date_selector = "#EventAdd_end_date";
        EventAdd_end_date_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 1,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        EventAdd_end_date_dataPickerOptions.defaultDate = new Date("08/20/2015");

        Apperyio.__registerComponent('end_date', new Apperyio.ApperyMobileDatePickerComponent("EventAdd_end_date", EventAdd_end_date_dataPickerOptions));

    };

    // screen elements handler


    function EventAdd_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#EventAdd_mobileheader [name="btn_home"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'flip',
                        reverse: false
                    });

                }
            },
        }, '#EventAdd_mobileheader [name="btn_home"]');

        $(document).off("click", '#EventAdd_mobilecontainer [name="btn_submit_event"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        EventAdd.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    setTimeout(function() {
                        window.location = 'EventView.html';
                    }, 0);

                }
            },
        }, '#EventAdd_mobilecontainer [name="btn_submit_event"]');

    };

    $(document).off("pagebeforeshow", "#EventAdd").on("pagebeforeshow", "#EventAdd", function(event, ui) {
        Apperyio.CurrentScreen = "EventAdd";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    EventAdd_onLoad();
};

$(document).off("pagecreate", "#EventAdd").on("pagecreate", "#EventAdd", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    EventAdd_js();
});