/*
 * JS for Logout generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function Logout_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {

    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Logout';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Logout_onLoad = function() {
            Logout_elementsExtraJS();

/*
Apperyio.storage.storageVariable.update("$['sess_con']", "");
Apperyio.storage.storageVariable.update("$['sess_acc']", "");
Apperyio.storage.storageVariable.update("$['sess_facebook']", "");
Apperyio.storage.storageVariable.update("$['allow_fb_rego']", "");
Apperyio.storage.storageVariable.update("$['sess_google']", "");
Apperyio.storage.storageVariable.update("$['sess_linkedin']", "");
*/
            Apperyio.storage.sess_con.set("");
            Apperyio.storage.sess_acc.set("");
            Apperyio.storage.sess_facebook.set("");
            Apperyio.storage.allow_fb_rego.set("");
            Apperyio.storage.sess_google.set("");
            Apperyio.storage.sess_linkedin.set("");
            setTimeout(function() {
                window.location = 'startScreen.html';
            }, 0);

            Logout_deviceEvents();
            Logout_windowEvents();
            Logout_elementsEvents();
        };

    // screen window events


    function Logout_windowEvents() {

        $('#Logout').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Logout_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Logout_elementsExtraJS() {
        // screen (Logout) extra code

    };

    // screen elements handler


    function Logout_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Logout").on("pagebeforeshow", "#Logout", function(event, ui) {
        Apperyio.CurrentScreen = "Logout";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Logout_onLoad();
};

$(document).off("pagecreate", "#Logout").on("pagecreate", "#Logout", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Logout_js();
});