/*
 * JS for MyProfile generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function MyProfile_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'MyProfile_mobilebutton_2',
        'mobilegrid_3': 'MyProfile_mobilegrid_3',
        'mobilegridcell_4': 'MyProfile_mobilegridcell_4',
        'mobilelabel_13': 'MyProfile_mobilelabel_13',
        'mobilegridcell_14': 'MyProfile_mobilegridcell_14',
        'first_name': 'MyProfile_first_name',
        'mobilegridcell_6': 'MyProfile_mobilegridcell_6',
        'mobilelabel_19': 'MyProfile_mobilelabel_19',
        'mobilegridcell_15': 'MyProfile_mobilegridcell_15',
        'last_name': 'MyProfile_last_name',
        'mobilegridcell_8': 'MyProfile_mobilegridcell_8',
        'mobilelabel_20': 'MyProfile_mobilelabel_20',
        'mobilegridcell_16': 'MyProfile_mobilegridcell_16',
        'email': 'MyProfile_email',
        'mobilegridcell_10': 'MyProfile_mobilegridcell_10',
        'contact_id': 'MyProfile_contact_id',
        'mobilegridcell_17': 'MyProfile_mobilegridcell_17',
        'mobilegridcell_12': 'MyProfile_mobilegridcell_12',
        'mobilegridcell_18': 'MyProfile_mobilegridcell_18',
        'mobilelabel_34': 'MyProfile_mobilelabel_34',
        'mobilegrid_35': 'MyProfile_mobilegrid_35',
        'mobilegridcell_36': 'MyProfile_mobilegridcell_36',
        'mobilelabel_41': 'MyProfile_mobilelabel_41',
        'mobilegridcell_37': 'MyProfile_mobilegridcell_37',
        'tog_offline_sync_enable': 'MyProfile_tog_offline_sync_enable',
        'mobilegridcell_38': 'MyProfile_mobilegridcell_38',
        'mobilegridcell_39': 'MyProfile_mobilegridcell_39',
        'mobilelabel_21': 'MyProfile_mobilelabel_21',
        'mobilegrid_22': 'MyProfile_mobilegrid_22',
        'mobilegridcell_23': 'MyProfile_mobilegridcell_23',
        'lbl_auto_logging_enabled': 'MyProfile_lbl_auto_logging_enabled',
        'mobilegridcell_24': 'MyProfile_mobilegridcell_24',
        'auto_logging_enabled': 'MyProfile_auto_logging_enabled',
        'mobilegridcell_25': 'MyProfile_mobilegridcell_25',
        'lbl_auto_logging_interval': 'MyProfile_lbl_auto_logging_interval',
        'mobilegridcell_26': 'MyProfile_mobilegridcell_26',
        'auto_logging_interval': 'MyProfile_auto_logging_interval',
        'auto_logging_interval-0': 'MyProfile_auto_logging_interval-0',
        'mobilegridcell_30': 'MyProfile_mobilegridcell_30',
        'lbl_auto_logging_distance': 'MyProfile_lbl_auto_logging_distance',
        'mobilegridcell_31': 'MyProfile_mobilegridcell_31',
        'auto_logging_distance': 'MyProfile_auto_logging_distance',
        'auto_logging_distance-0': 'MyProfile_auto_logging_distance-0',
        'mobilegridcell_32': 'MyProfile_mobilegridcell_32',
        'mobilegridcell_33': 'MyProfile_mobilegridcell_33'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["MyProfile_ContactsList_onsuccess_mapping_0"] = {
        "homeScreen": "MyProfile",
        "directions": [

        {
            "from_name": "ContactsList",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "MyProfile",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['contacts'][0]['first_name']",
                "target": "$['first_name:text']"

            },

            {

                "source": "$['body']['contacts'][0]['last_name']",
                "target": "$['last_name:text']"

            },

            {

                "source": "$['body']['contacts'][0]['id']",
                "target": "$['contact_id:text']"

            },

            {

                "source": "$['body']",
                "target": "$['mobilegrid_3']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["MyProfile_ContactsList_onbeforesend_mapping_0"] = {
        "homeScreen": "MyProfile",
        "directions": [

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "ContactsList",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "Contacts"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['contact_id']"

            },

            {

                "source": "$",
                "target": "$['parameters']['val']"

            },

            {

                "source": "$",
                "target": "$['parameters']['sess_con']"

            }

            ]
        },

        {
            "from_name": "sess_acc",
            "from_type": "SESSION_STORAGE",

            "to_name": "ContactsList",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects"
                },
                "parameters": {
                    "action": "list",
                    "valtype": "Contacts"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['account_id']"

            },

            {

                "source": "$",
                "target": "$['parameters']['sess_acc']"

            }

            ]
        },

        {
            "from_name": "sess_con",
            "from_type": "SESSION_STORAGE",

            "to_name": "MyProfile",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['contact_id:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.ContactsList = Apperyio.datasources.ContactsList = new Apperyio.DataSource(RESTService_Contacts_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["MyProfile_ContactsList_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["MyProfile_ContactsList_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'MyProfile';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var MyProfile_onLoad = function() {
            MyProfile_elementsExtraJS();

            try {
                ContactsList.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            setAttribute_('MyProfile_auto_logging_enabled', 'toggled', $a.storage["configurations"].get("$['auto_logging_enabled']"));
            $('[id="MyProfile_auto_logging_enabled"]').refresh();
            setAttribute_('MyProfile_tog_offline_sync_enable', 'toggled', $a.storage["configurations"].get("$['offline_sync_enable']"));
            $('[id="MyProfile_tog_offline_sync_enable"]').refresh();
            setAttribute_('MyProfile_auto_logging_distance', 'selectedIndex', $a.storage["configurations"].get("$['auto_logging_distance']"));
            $('[id="MyProfile_auto_logging_distance"]').refresh();
            setAttribute_('MyProfile_auto_logging_interval', 'selectedIndex', $a.storage["configurations"].get("$['auto_logging_interval']"));
            $('[id="MyProfile_auto_logging_interval"]').refresh();

            MyProfile_deviceEvents();
            MyProfile_windowEvents();
            MyProfile_elementsEvents();
        };

    // screen window events


    function MyProfile_windowEvents() {

        $('#MyProfile').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function MyProfile_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function MyProfile_elementsExtraJS() {
        // screen (MyProfile) extra code

        /* tog_offline_sync_enable */

        $("#MyProfile_tog_offline_sync_enable").parent().find(".ui-flipswitch-on").attr("tabindex", "6");

        /* auto_logging_enabled */

        $("#MyProfile_auto_logging_enabled").parent().find(".ui-flipswitch-on").attr("tabindex", "2");

        /* auto_logging_interval */

        $("#MyProfile_auto_logging_interval").parent().find("a.ui-btn").attr("tabindex", "4");

        /* auto_logging_distance */

        $("#MyProfile_auto_logging_distance").parent().find("a.ui-btn").attr("tabindex", "5");

    };

    // screen elements handler


    function MyProfile_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#MyProfile_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'startScreen.html';
                    }, 0);

                }
            },
        }, '#MyProfile_mobileheader [name="mobilebutton_2"]');

        $(document).off("change", '#MyProfile_mobilecontainer [name="tog_offline_sync_enable"]').on({
            change: function(event) {
                try {
                    $a.storage["configurations"].update("$['offline_sync_enable']", $a.c15r($a.UIHandler.resolveGeneratedComponent('tog_offline_sync_enable', this), 'get', 'toggled'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#MyProfile_mobilecontainer [name="tog_offline_sync_enable"]');

        $(document).off("change", '#MyProfile_mobilecontainer [name="auto_logging_enabled"]').on({
            change: function(event) {
                try {
                    $a.storage["configurations"].update("$['auto_logging_enabled']", $a.c15r($a.UIHandler.resolveGeneratedComponent('auto_logging_enabled', this), 'get', 'toggled'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#MyProfile_mobilecontainer [name="auto_logging_enabled"]');

        $(document).off("change", '#MyProfile_mobilecontainer [name="auto_logging_interval"]').on({
            change: function(event) {
                try {
                    $a.storage["configurations"].update("$['auto_logging_interval']", $a.c15r($a.UIHandler.resolveGeneratedComponent('auto_logging_interval', this), 'get', 'selectedMenuItem'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#MyProfile_mobilecontainer [name="auto_logging_interval"]');

        $(document).off("change", '#MyProfile_mobilecontainer [name="auto_logging_distance"]').on({
            change: function(event) {
                try {
                    $a.storage["configurations"].update("$['auto_logging_distance']", $a.c15r($a.UIHandler.resolveGeneratedComponent('auto_logging_distance', this), 'get', 'selectedMenuItem'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#MyProfile_mobilecontainer [name="auto_logging_distance"]');

    };

    $(document).off("pagebeforeshow", "#MyProfile").on("pagebeforeshow", "#MyProfile", function(event, ui) {
        Apperyio.CurrentScreen = "MyProfile";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    MyProfile_onLoad();
};

$(document).off("pagecreate", "#MyProfile").on("pagecreate", "#MyProfile", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    MyProfile_js();
});