/*
 * JS for Registration generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4f47d7f5-362a-4b3c-8a2f-a4014ed03a5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "EventAdd",
    "location": "EventAdd.html"
}, {
    "name": "EventView",
    "location": "EventView.html"
}, {
    "name": "ContactsSync",
    "location": "ContactsSync.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "Logout",
    "location": "Logout.html"
}, {
    "name": "MyProfile",
    "location": "MyProfile.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Registration",
    "location": "Registration.html"
}, {
    "name": "Facebook_Return",
    "location": "Facebook_Return.html"
}, {
    "name": "AccountDetails",
    "location": "AccountDetails.html"
}];

function Registration_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_35': 'Registration_mobilebutton_35',
        'account_name': 'Registration_account_name',
        'username': 'Registration_username',
        'password': 'Registration_password',
        'first_name': 'Registration_first_name',
        'last_name': 'Registration_last_name',
        'email': 'Registration_email',
        'button_register': 'Registration_button_register',
        'rego_message': 'Registration_rego_message'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Registration_UserRegistration_onsuccess_mapping_0"] = {
        "homeScreen": "Registration",
        "directions": [

        {
            "from_name": "UserRegistration",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "sess_con",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sess_con']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "UserRegistration",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "sess_acc",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sess_acc']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "UserRegistration",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "val",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sess_con']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "UserRegistration",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Registration",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['api_message']",
                "target": "$['rego_message:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Registration_UserRegistration_onbeforesend_mapping_0"] = {
        "homeScreen": "Registration",
        "directions": [

        {
            "from_name": "Registration",
            "from_type": "UI",

            "to_name": "UserRegistration",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "application": "sharedeffects",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {
                    "api_key": "de8891b2-4407-b4c4-f153-51cb64bac59e",
                    "action": "auth"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['account_name:text']",
                "target": "$['body']['account_name']"

            },

            {

                "source": "$['username:text']",
                "target": "$['body']['username']"

            },

            {

                "source": "$['password:text']",
                "target": "$['body']['password']"

            },

            {

                "source": "$['first_name:text']",
                "target": "$['body']['first_name']"

            },

            {

                "source": "$['last_name:text']",
                "target": "$['body']['last_name']"

            },

            {

                "source": "$['email:text']",
                "target": "$['body']['email']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.UserRegistration = Apperyio.datasources.UserRegistration = new Apperyio.DataSource(RESTService_Registration, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Registration_UserRegistration_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Registration_UserRegistration_onsuccess_mapping_0"]);
            toggle('Registration_rego_message', 'mob', 'true');
            Apperyio.navigateTo('MyProfile', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Registration';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Registration_onLoad = function() {
            Registration_elementsExtraJS();

            var email = localStorage.getItem('email');
            Apperyio('email').text(email);
            var password = localStorage.getItem('password');
            Apperyio('password').text(password);
            var account_name = localStorage.getItem('account_name');
            Apperyio('account_name').text(account_name);
            var username = localStorage.getItem('username');
            Apperyio('username').text(username);
            var first_name = localStorage.getItem('first_name');
            Apperyio('first_name').text(first_name);
            var last_name = localStorage.getItem('last_name');
            Apperyio('last_name').text(last_name);;

            Registration_deviceEvents();
            Registration_windowEvents();
            Registration_elementsEvents();
        };

    // screen window events


    function Registration_windowEvents() {

        $('#Registration').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Registration_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Registration_elementsExtraJS() {
        // screen (Registration) extra code

    };

    // screen elements handler


    function Registration_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Registration_mobileheader [name="mobilebutton_35"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#Registration_mobileheader [name="mobilebutton_35"]');

        $(document).off("click", '#Registration_mobilecontainer [name="button_register"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var email = Apperyio('email').val();
                    localStorage.setItem('email', email);
                    var password = Apperyio('password').val();
                    localStorage.setItem('password', password);
                    var account_name = Apperyio('account_name').val();
                    localStorage.setItem('account_name', account_name);
                    var username = Apperyio('username').val();
                    localStorage.setItem('username', username);
                    var first_name = Apperyio('first_name').val();
                    localStorage.setItem('first_name', first_name);
                    var last_name = Apperyio('last_name').val();
                    localStorage.setItem('last_name', last_name);
                    try {
                        UserRegistration.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Registration_mobilecontainer [name="button_register"]');

    };

    $(document).off("pagebeforeshow", "#Registration").on("pagebeforeshow", "#Registration", function(event, ui) {
        Apperyio.CurrentScreen = "Registration";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Registration_onLoad();
};

$(document).off("pagecreate", "#Registration").on("pagecreate", "#Registration", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Registration_js();
});