<?php

$synchkey = "bxasvcvdytcvaycvayvdya";  // create random one
$glb_domain = "saloob.com";
$glb_home_url = "http://".$glb_domain;
$glb_app_dir = "m";
$is_subdomain = 0;
$subdomain = "";
$is_ssl = 0;
$default_lingo = "en";
$portal_title = "Timemappers by Saloob, Inc.";
$portal_style = "css/timemappers.css";
$portal_system_style = "css/style.php";
$portal_style_images = "timemappers";
$portal_logo = "timemappers/logo.gif";
$portal_logo_height = "50";
$portal_logo_width = "210";
$portal_logo_title = $portal_title;
$portal_url = $glb_home_url."/".$glb_app_dir;
$portal_url_title = $portal_title;
$portal_copyright_text = "Copyright 2007+<BR>Saloob, Inc. All rights reserved";
$portal_copyright_url = "http://www.saloob.com";

$synchdbconfig = array (
    'db_host_name' => '192.168.1.11',
    'db_user_name' => 'saloobdb',
    'db_password' => 'spicemeup72',
    'db_name' => 'saloob',
    'db_type' => 'mysql',
  );
  
?>
